### ISSUE TITLE
disable render_block in extended template

### ISSUE THREAD

**Issue by oppianmatt** [ojii/django-sekizai#64]
I have template that extends from base. Base has a `render_block js` in it. In the template that extends from base I want to disable that render_block. I can't see a way how to do it, not with the restrictions.

You can't put it in a block which you empty out in the extended template.

You can't wrap it with an if statement since nothing can wrap it.

This is what I've resorted to disable it.

base.html:

```
{# hack to get around sekizai #}
{% block pre_js_block %}{% endblock %}
{% render_block "js" %}
{% block post_js_block %}{% endblock %}
```

extends.html:

```
{% extends 'base.html' %}

{% block pre_js_block %}
  <!--
{% endblock %}

{% block post_js_block %}
  -->
{% endblock %}
```

As you can see I've resorted to putting a html start and end comment around it. So technically it's not disabled, but the output is ignored by the browser.

**Comment by ojii** [comment]
This isn't possible because of how the Django template engine works. You can however conditionally call `addtoblock` if that's a possible solution for your use case, or use two base templates (one with one without the `render_block`).

If you can elaborate more on your use-case, i might be able to suggest better workarounds/solutions.
